"""user tokens

Revision ID: 991c134f9350
Revises: 395ffa46f8fa
Create Date: 2020-08-28 15:16:27.527174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991c134f9350'
down_revision = '395ffa46f8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
